In [1]:
# data type conversion: proccess of converting data from one type to another

In [2]:
import pandas as pd
import numpy as np

In [3]:
data = {
    'AGE': ['45','22','30'],
    'Salary':[40000,50000,60000],
    'Join_date':['2025-01-01','2025-07-15', '2025-04-20']
}

df =pd.DataFrame(data)
print(df)

  AGE  Salary   Join_date
0  45   40000  2025-01-01
1  22   50000  2025-07-15
2  30   60000  2025-04-20

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   AGE        3 non-null      object
 1   Salary     3 non-null      int64
 2   Join_date  3 non-null      object
dtypes: int64(1), object(2)
memory usage: 204.0+ bytes

In [5]:
# convert to numeric type
df['AGE'] = pd.to_numeric(df['AGE'])

# convert to int (age is formated in integer)
df['Age'] = df['AGE'].astype(int)

In [6]:
# convert to date type
df['Join_date'] = pd.to_datetime(df['Join_date'])

In [8]:
print(df.dtypes)

AGE                   int64
Salary                int64
Join_date    datetime64[ns]
Age                   int64
dtype: object

In [9]:
# conversion ensures that correst mathematical operations run smoothly

In [10]:
# add new column for demonstration
df['Height'] = ['5.8', '6.1','5.5']
df['Department'] = ['HR', 'Finance', 'HR']
df['Experience'] = ['2', 'three', '4']

print(df)

   AGE  Salary  Join_date  Age Height Department Experience
0   45   40000 2025-01-01   45    5.8         HR          2
1   22   50000 2025-07-15   22    6.1    Finance      three
2   30   60000 2025-04-20   30    5.5         HR          4

In [13]:
# convert to float type
df['Height'] = df['Height'].astype('float')

In [14]:
# convert to category
df['Department'] = df['Department'].astype('category')

In [15]:
# convert to number with errors
df['Experience'] = pd.to_numeric(df['Experience'], errors = 'coerce')

In [17]:
print(df)

   AGE  Salary  Join_date  Age  Height Department  Experience
0   45   40000 2025-01-01   45     5.8         HR         2.0
1   22   50000 2025-07-15   22     6.1    Finance         NaN
2   30   60000 2025-04-20   30     5.5         HR         4.0

In [18]:
# cleaning messy dataset

In [21]:
data = {
    'Name': ['Alice','Bob', None,'David', 'Alice'],
    'Age': ['25','thirty','35', None, '25'],
    'Salary':[50000,60000, None, 55000, 50000],
    'Join_date':['2025-01-01', 'not_availabel', '2025-05-01', '2025-11-01', '2025-01-01']
}

df = pd.DataFrame(data)
df

    Name     Age   Salary      Join_date
0  Alice      25  50000.0     2025-01-01
1    Bob  thirty  60000.0  not_availabel
2   None      35      NaN     2025-05-01
3  David    None  55000.0     2025-11-01
4  Alice      25  50000.0     2025-01-01

In [23]:
# check for data type
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Name       4 non-null      object
 1   Age        4 non-null      object
 2   Salary     4 non-null      float64
 3   Join_date  5 non-null      object
dtypes: float64(1), object(3)
memory usage: 292.0+ bytes

In [25]:
# summary data
print(df.describe(include = 'all'))

         Name  Age        Salary   Join_date
count       4    4      4.000000           5
unique      3    3           NaN           4
top     Alice   25           NaN  2025-01-01
freq        2    2           NaN           2
mean      NaN  NaN  53750.000000         NaN
std       NaN  NaN   4787.135539         NaN
min       NaN  NaN  50000.000000         NaN
25%       NaN  NaN  50000.000000         NaN
50%       NaN  NaN  52500.000000         NaN
75%       NaN  NaN  56250.000000         NaN
max       NaN  NaN  60000.000000         NaN

In [26]:
# check for missing value
df.isnull().sum()

Name         1
Age          1
Salary       1
Join_date    0
dtype: int64

In [28]:
# clean data

# Age
df['Age'] = df['Age'].replace('thirty', np.nan)
df['Age'] = pd.to_numeric(df['Age'], errors = 'coerce')

df['Age'] = df['Age'].fillna(df['Age'].mean())

# Name
df['Name'] = df['Name'].fillna('Unknown')

# Salary
df['Salary'] = df['Salary'].ffill()

In [29]:
# convert datatypes

# Join_date
df['Join_date'] = pd.to_datetime(df['Join_date'], errors = 'coerce')

In [30]:
# remove duplicates
df = df.drop_duplicates()

In [39]:
print(df)
print('Data type \n', df.dtypes)

      Name        Age   Salary  Join_date
0    Alice  25.000000  50000.0 2025-01-01
1      Bob  28.333333  60000.0        NaT
2  Unknown  35.000000  60000.0 2025-05-01
3    David  28.333333  55000.0 2025-11-01
Data type
 Name                 object
Age                 float64
Salary              float64
Join_date    datetime64[ns]
dtype: object

In [40]:
# rename variables
df = df.rename(columns = {'Name': 'First_name', 'Salary': 'income'})

In [41]:
print(df)

  First_name        Age   income  Join_date
0      Alice  25.000000  50000.0 2025-01-01
1        Bob  28.333333  60000.0        NaT
2    Unknown  35.000000  60000.0 2025-05-01
3      David  28.333333  55000.0 2025-11-01