In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data = {
    'name': ['Alice', 'Bob', 'Charles', 'David', 'Eva', 'Phuc'],
    'age': ['25', 'np.nan', '30', '29', 'NaN', '25'],
    'gender': ['female','male','male','np.nan','female','female'],
    'country': ['USA', 'usa', 'canada', 'CANADA', 'UK', 'USA'],
    'quantity': [2,1,3,5,2,2],
    'unit_price': [20,15,np.nan,10,30,20]
}

df = pd.DataFrame(data)
df

      name     age  gender country  quantity  unit_price
0    Alice      25  female     USA         2        20.0
1      Bob  np.nan    male     usa         1        15.0
2  Charles      30    male  canada         3         NaN
3    David      29  np.nan  CANADA         5        10.0
4      Eva     NaN  female      UK         2        30.0
5     Phuc      25  female     USA         2        20.0

In [ ]:
# data cleaning
# handle missing values - mean, median, mode or remove

In [ ]:
# filling with 0
df.fillna(0)

      name     age  gender country  quantity  unit_price
0    Alice      25  female     USA         2        20.0
1      Bob  np.nan    male     usa         1        15.0
2  Charles      30    male  canada         3         0.0
3    David      29  np.nan  CANADA         5        10.0
4      Eva     NaN  female      UK         2        30.0
5     Phuc      25  female     USA         2        20.0

In [ ]:
# drop value
df.dropna()

    name     age  gender country  quantity  unit_price
0  Alice      25  female     USA         2        20.0
1    Bob  np.nan    male     usa         1        15.0
3  David      29  np.nan  CANADA         5        10.0
4    Eva     NaN  female      UK         2        30.0
5   Phuc      25  female     USA         2        20.0

In [ ]:
# drop duplicate values
df.drop_duplicates()

      name     age  gender country  quantity  unit_price
0    Alice      25  female     USA         2        20.0
1      Bob  np.nan    male     usa         1        15.0
2  Charles      30    male  canada         3         NaN
3    David      29  np.nan  CANADA         5        10.0
4      Eva     NaN  female      UK         2        30.0
5     Phuc      25  female     USA         2        20.0

In [ ]:
# correcting datatypes
# country
df['country'] = df['country'].str.lower()
df

      name     age  gender country  quantity  unit_price
0    Alice      25  female     usa         2        20.0
1      Bob  np.nan    male     usa         1        15.0
2  Charles      30    male  canada         3         NaN
3    David      29  np.nan  canada         5        10.0
4      Eva     NaN  female      uk         2        30.0
5     Phuc      25  female     usa         2        20.0

In [ ]:
# age - biến cột age thành số nguyên sạch

# chuyển cột age thành kiểu số - không chuyển được thì sẽ biến thành NaN (errors = coerce)
df['age'] = pd.to_numeric(df['age'], errors = 'coerce')

# fill các ô NaN bằng giá trị trung viị của cột
df['age'] = df['age'].fillna(df['age'].median())

# chuyển dữ liệu từ float => int cho phù hợp với tính chất của age
df['age'] = df['age'].astype(int)

In [ ]:
# data preparation
# make data ready for analysis or modeling

In [ ]:
# feature engineering - create columns from existing ones
df

      name  age  gender country  quantity  unit_price
0    Alice   25  female     usa         2        20.0
1      Bob   27    male     usa         1        15.0
2  Charles   30    male  canada         3         NaN
3    David   29  np.nan  canada         5        10.0
4      Eva   27  female      uk         2        30.0
5     Phuc   25  female     usa         2        20.0

In [ ]:
df['total_price'] = df['unit_price'] * df['quantity']
print(df)

      name  age  gender country  quantity  unit_price  total_price
0    Alice   25  female     usa         2        20.0         40.0
1      Bob   27    male     usa         1        15.0         15.0
2  Charles   30    male  canada         3         NaN          NaN
3    David   29  np.nan  canada         5        10.0         50.0
4      Eva   27  female      uk         2        30.0         60.0
5     Phuc   25  female     usa         2        20.0         40.0

In [ ]:
# encoding categorial values - converting text labels => specific numbers
pd.get_dummies(df['gender'])

   female   male  np.nan
0    True  False   False
1   False   True   False
2   False   True   False
3   False  False    True
4    True  False   False
5    True  False   False

In [ ]:
# scaling & normalization - using in ML models
!pip install scikit-learn

Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: numpy>=1.19.5 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (2.0.2)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)

In [ ]:
from sklearn.preprocessing import MinMaxScaler
# chuẩn hóa dữ liệu về khoảng [0,1]

In [ ]:
scaler = MinMaxScaler()
df['income'] = scaler.fit_transform(df[['total_price']])

In [ ]:
df

      name  age  gender country  quantity  unit_price  total_price    income
0    Alice   25  female     usa         2        20.0         40.0  0.555556
1      Bob   27    male     usa         1        15.0         15.0  0.000000
2  Charles   30    male  canada         3         NaN          NaN       NaN
3    David   29  np.nan  canada         5        10.0         50.0  0.777778
4      Eva   27  female      uk         2        30.0         60.0  1.000000
5     Phuc   25  female     usa         2        20.0         40.0  0.555556

In [ ]:
# splitting the data (train/test) - dùng sklearn cho dữ liệu không mang tính thời gian
from sklearn.model_selection import train_test_split
train, test = train_test_split(df, test_size = 0.2)

In [ ]:
# chia dữ liệu làm 3 (train/val/test) - cho dữ liệu không mang tính thời gian
# bước 1: tách test trước
from sklearn.model_selection import train_test_split
train_val, test = train_test_split(df, testsize = 0.15, random_state = 42)

# bước 2: tách train và val
train, val = train_test_split(train_val, test_size = 0.176, random_state = 42)
# 0.176 vì 0.15/0.85 = 0.176 => 15% tổng

In [ ]:
# split data - using for panel data or time-series
# ví dụ thôi chứ cell này ko chạy được nha
# b1: sắp xếp theo thời gian
df = df.sort_values('date')

# b2: tính index
split_idx = int(len(df) * 0.8)
# len(df): lấy tổng số dòng
# int => chuyển sang số nguyên
train = df.iloc[:split_idx] # lấy từ dòng đầu tiên đến dòng 80%
test = df.iloc[split_idx:] # lấy từ dòng 80% đến cuối

In [ ]:
# chia làm train - val - test
# ví dụ thôi chứ cell này ko chạy được nha
# b1: sắp xếp theo thời gian
df = df.sort_values('date')

# b2: tính index
n = len(df) # tổng số dòng của df
train_end = int(n * 0.6)
val_end = int(n * 0.85)

# b3: chia dữ liệu
train = df.iloc[:train_end]
val = df.iloc[train_end:val_end]
test = df.iloc[val_end:]