In [2]:
# groupby is used to split data into groups based on criteria like categories or values in a column
# aggregating: using functions such as sum, count, mean,... and combine them together

In [3]:
import pandas as pd

In [15]:
data = {
    'Region':['East', 'West', 'East', 'South', 'North', 'North'],
    'Name':['Alice', 'Bob', 'Charles', 'David', 'Eva', 'Darwin'],
    'Sales':[200,150,300,100,400,100]
}

df = pd.DataFrame(data)

In [16]:
df.head()

  Region     Name  Sales
0   East    Alice    200
1   West      Bob    150
2   East  Charles    300
3  South    David    100
4  North      Eva    400

In [17]:
# group data by region
grouped = df.groupby('Region')

In [18]:
print(grouped)

<pandas.core.groupby.generic.DataFrameGroupBy object at 0x7b02b31f1a60>

In [19]:
# apply aggregation functions
grouped['Sales'].sum()

Region
East     500
North    500
South    100
West     150
Name: Sales, dtype: int64

In [20]:
grouped['Sales'].mean()

Region
East     250.0
North    250.0
South    100.0
West     150.0
Name: Sales, dtype: float64

In [21]:
grouped['Sales'].count()

Region
East     2
North    2
South    1
West     1
Name: Sales, dtype: int64

In [22]:
# multiple aggregations
grouped['Sales'].agg(['sum', 'mean', 'count','max', 'min'])

        sum   mean  count  max  min
Region
East    500  250.0      2  300  200
North   500  250.0      2  400  100
South   100  100.0      1  100  100
West    150  150.0      1  150  150

In [24]:
# group by multiple column
# đây là code làm nhanh
df.groupby(['Region', 'Sales'])['Sales'].agg(['sum', 'mean', 'count', 'max', 'min'])

# làm chậm thì sẽ như này
'''
grouped_multiple = df.groupby(['Region', 'Sales'])
group_multiple['Sales'].agg(['sum', 'mean', 'count', 'max', 'min'])
'''

              sum   mean  count  max  min
Region Sales
East   200    200  200.0      1  200  200
       300    300  300.0      1  300  300
North  100    100  100.0      1  100  100
       400    400  400.0      1  400  400
South  100    100  100.0      1  100  100
West   150    150  150.0      1  150  150

In [25]:
# convert the result back to a df with the default indexing
grouped['Sales'].sum().reset_index()

  Region  Sales
0   East    500
1  North    500
2  South    100
3   West    150

In [26]:
# apply sorting
grouped['Sales'].sum().sort_values(ascending = False)

Region
East     500
North    500
West     150
South    100
Name: Sales, dtype: int64

In [28]:
# value counts and unique values in pandas
# useful in exploring categorical data

In [29]:
data = {
    'City':['New York', 'London', 'New York', 'Paris', 'London', 'Berlin', 'Paris', 'Paris'],
    'Gender':['Male', 'Female', 'Female', 'Male', 'Female', 'Male', 'Female', 'Male']
}

df = pd.DataFrame(data)

In [30]:
df

       City  Gender
0  New York    Male
1    London  Female
2  New York  Female
3     Paris    Male
4    London  Female
5    Berlin    Male
6     Paris  Female
7     Paris    Male

In [31]:
# value counts - đếm tần suất từng biến
df['City'].value_counts()

City
Paris       3
New York    2
London      2
Berlin      1
Name: count, dtype: int64

In [32]:
df['Gender'].value_counts()

Gender
Male      4
Female    4
Name: count, dtype: int64

In [33]:
# get percentage instead of raw count
df['Gender'].value_counts(normalize = True)

Gender
Male      0.5
Female    0.5
Name: proportion, dtype: float64

In [34]:
# unique fuction
df['City'].unique()

array(['New York', 'London', 'Paris', 'Berlin'], dtype=object)

In [35]:
df['Gender'].unique()

array(['Male', 'Female'], dtype=object)

In [36]:
# count the number of unique values
df['City'].nunique()

4

In [40]:
df['Gender'].unique()

array(['Male', 'Female'], dtype=object)