In [102]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [103]:
data1 = {
    'Name': ['Alice', 'Bob', 'Charles', 'David', 'Eva'],
    'Age': [24, np.nan, 30, 22, np.nan],
    'Gender':['F','M', np.nan,'M', 'F'],
    "Score": [85,90, np.nan, 66, 76]
}

df = pd.DataFrame(data1)
df

      Name   Age Gender  Score
0    Alice  24.0      F   85.0
1      Bob   NaN      M   90.0
2  Charles  30.0    NaN    NaN
3    David  22.0      M   66.0
4      Eva   NaN      F   76.0

In [104]:
# check for missing values
df.isnull().sum()

Name      0
Age       2
Gender    1
Score     1
dtype: int64

In [105]:
print(df.isnull())

    Name    Age  Gender  Score
0  False  False   False  False
1  False   True   False  False
2  False  False    True   True
3  False  False   False  False
4  False   True   False  False

In [106]:
df_drop_any = df.dropna() # xóa dòng nếu dòng có  NaN - chỉ cần dòng có NaN là xóa

In [107]:
# drop rows where values are missing
df_drop_all = df.dropna(how = 'all') # xóa dòng nếu tất cả các giá trị của dòng đều là NaN

In [108]:
# drop column
df_drop_column = df.dropna(axis = 1)

In [109]:
# filling missing data

In [110]:
# fil with a specific value
df_fill_constant = df.fillna(0)

In [111]:
# fill with mean/median/mode
df['Age'] = df['Age'].fillna(df['Age'].mean())
df['Score'] = df['Score'].fillna(df['Score'].median())
df['Gender'] = df['Gender'].fillna(df['Gender'].mode()[0])

In [112]:
print(df)

      Name        Age Gender  Score
0    Alice  24.000000      F   85.0
1      Bob  25.333333      M   90.0
2  Charles  30.000000      F   80.5
3    David  22.000000      M   66.0
4      Eva  25.333333      F   76.0

In [113]:
# fill foward
df_ffill = df.ffill()

In [114]:
# fil backward
df_bfill = df.bfill()

In [115]:
# interpolating with missing data - nội suy - numerical
df_interpolated = df.interpolate() # old version

/tmp/ipython-input-2888464450.py:2: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df_interpolated = df.interpolate() # old version

In [116]:
# new version
# vì trong các phiên bản mới interpolate chỉ dùng cho numeric data nên phải dùng selec_dtypes để lựa num data
df_interpolated_new = df.select_dtypes(include = 'number').interpolate()

In [117]:
print(df.isnull().sum())

Name      0
Age       0
Gender    0
Score     0
dtype: int64

In [118]:
# Data filtering using conditionals

In [119]:
data = {
    'Name': ['Alice', 'Bob', 'Charles', 'David', 'Eva'],
    'Age': [2,37,30,22,55],
    'Gender':['F','M', 'M','M', 'F'],
    "Salary": [50000,60000,5500,80000,45000]
}

df1 = pd.DataFrame(data)

In [120]:
print(df1)

      Name  Age Gender  Salary
0    Alice    2      F   50000
1      Bob   37      M   60000
2  Charles   30      M    5500
3    David   22      M   80000
4      Eva   55      F   45000

In [121]:
condition = df1['Age'] >= 30

In [122]:
print(condition)

0    False
1     True
2     True
3    False
4     True
Name: Age, dtype: bool

In [123]:
# filter dataframe
print(df1[condition])
df1[condition]

      Name  Age Gender  Salary
1      Bob   37      M   60000
2  Charles   30      M    5500
4      Eva   55      F   45000

      Name  Age Gender  Salary
1      Bob   37      M   60000
2  Charles   30      M    5500
4      Eva   55      F   45000

In [124]:
filtered_df = df1[(df1['Age'] > 20) & (df1['Gender'] == "M")]
print(filtered_df)

      Name  Age Gender  Salary
1      Bob   37      M   60000
2  Charles   30      M    5500
3    David   22      M   80000